### ISSUE TITLE
test in smex-extract-commands-from-features may be unintentionally trivial

### ISSUE THREAD

**Issue by genovese** [nonsequitur/smex#48]
This is a terrific package. Thanks!

In the function `smex-extract-commands-from-features` (on line 435 in current version of smex.el),
the test `(string-match mode-name (file-name-nondirectory feature-path))` is checking if the mode-name without the "-mode" matches a feature in the load history. 

But almost every path in the car of a load-history entry has an extension, except for a few files like (".recentf" "cookies" ".abbrev_defs" ".emacs").  None of these entries will ever match the mode name, and the test will always fail.

I suspect it should be `(string-match mode-name (file-name-sans-extension (file-name-nondirectory feature-path)))`, or the equivalent (e.g., `(file-name-base feature-path)`).

It's possible that you are going after a different type of entry in which you want the filename alone. But I thought I'd mention it just in case.

**Comment by nonsequitur** [comment]
`(string-match mode-name X)` succeeds, if `mode-name` is found anywhere `X`.

Eval the following to find out which feature files can be detected only in this way:

    ;; This mirrors smex-extract-commands-from-features
    (defun find-features (mode)
      (let ((library-path (symbol-file mode))
            (mode-name (symbol-name mode))
            commands)

        (string-match "\\(.+?\\)\\(-mode\\)?$" mode-name)
        ;; 'lisp-mode' -> 'lisp'
        (setq mode-name (match-string 1 mode-name))
        (if (string= mode-name "c") (setq mode-name "cc"))
        (setq mode-name (regexp-quote mode-name))

        (dolist (feature load-history)
          (let ((feature-path (car feature)))
            (when (and feature-path
                       (not (equal feature-path library-path))
                       (string-match mode-name (file-name-nondirectory
                                                feature-path)))
              (message "%s: %s matches %s"
                       mode
                       mode-name
                       (file-name-nondirectory feature-path))))
          commands)))

    (mapatoms (lambda (item)
                (when (and (symbolp item)
                           (fboundp item))
                  (when (string-match-p "-mode$" (symbol-name item))
                    (find-features item)))))
