### ISSUE TITLE
Feature request: Add helm frontend

### ISSUE THREAD

**Issue by wasamasa** [nonsequitur/smex#50]
To me it looks like smex is hardwired to make use of ido as frontend. While this is a fine choice, I think it would be better to abstract these parts away to allow for a helm frontend. [I did start writing one](https://github.com/wasamasa/dotemacs/blob/8362eccded97058a24305ff54171dcc02d747d50/unpublished/helm-smex.el), but it's far from ideal and would be better as part of upstream.

What I'm less sure about is how it would impact the rest of the project. Since Emacs doesn't really have the notion of optional dependencies, I'll guess I'll leave them as is and throw an error if the user chose the helm frontend with no helm installed.

This ticket serves as both reality check (is this a desirable feature for anyone else than me?) and personal reminder for me to create a pull request if still needed.

**Comment by PythonNut** [comment]
See also https://github.com/nonsequitur/smex/pull/51, which, when merged, should make this trivial to implement.

**Comment by wasamasa** [comment]
Closing as [helm-smex](https://github.com/ptrv/helm-smex) has become a thing.
