### ISSUE TITLE
Incompatible with Emacs 26

### ISSUE THREAD

**Issue by stapelberg** [nonsequitur/smex#71]
```
% emacs --version
GNU Emacs 26.0.90
```

I started `emacs -q`, switched to the `*scratch*` buffer, evaluated `(load-file "/tmp/smex/smex.el")`, ran M-x smex and saw: `Error in post-command-hook (ido-exhibit): (error "Attempt to modify read-only object" "insert-char")`.

When I type in the smex M-x prompt, only the last character is retained. E.g., when typing “foo”, I see “f”, “o”, “o”. This makes smex unusable.

**Comment by valignatev** [comment]
FWIW, smex works for me in emacs 26

**Comment by agumonkey** [comment]
same here, GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-07-05 (archlinux) and smex-20151212.2209 no issues.

**Comment by stapelberg** [comment]
Yeah, I’m using it on Emacs 26, too. Not sure what changed between when I reported the bug and now.

**Comment by wyuenho** [comment]
I have the same problem, seems related to ido-completing-read+

**Comment by wyuenho** [comment]
Actually, nevermind, it's related ido-vertical not requiring cl-lib
